Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -129,7 +129,12 @@ jobs:
 
       - name: Check Build production
         run: |
-          if [ ! -e "${{ github.workspace }}/apk/legado_*.apk" ]; then
+          if [ ! -d ${{ github.workspace }}/apk ]; then
+            echo "Build production not found! Check gradle logs."
+            exit 1
+          fi
+          cd ${{ github.workspace }}/apk/
+          if [ ! -e legado_*.apk ]; then
             echo "Build production not found! Check gradle logs."
             exit 1
           fi
