Update text.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -125,6 +125,13 @@ jobs:
         with:
           name: legado.${{ env.product }}.${{ env.type }}.mapping.missing_rules
           path: ${{ github.workspace }}/mapping/missing_rules.txt
+      - name: Check Build production
+        run: |
+          cd ${{ github.workspace }}/apk/
+          if [ ! -e legado_*.apk ]; then
+            echo "Build production not found! Check gradle logs."
+            exit 1
+          fi
 
   lanzou:
     needs: [ prepare, build ]
